export type RoadStep = {
  era: string;
  title: string;
  tool: string;
  scene: string;
  improved: string;
  unresolved: string;
  lesson: string;
  action: string;
  color: string;
};

export type ProgressRoad = {
  key: string;
  title: string;
  subtitle: string;
  question: string;
  steps: RoadStep[];
};

export const PROGRESS_ROADS: ProgressRoad[] = [
  {
    key: 'human-tools',
    title: 'History Of Human Tools',
    subtitle: 'How inventions changed the conditions of life.',
    question: 'What tools reduced suffering, opened agency, and created new responsibilities?',
    steps: [
      {
        era: 'Deep past',
        title: 'Fire',
        tool: 'warmth',
        scene: 'A walking figure passes a small fire and a protected circle of light.',
        improved: 'Fire made warmth, protection, cooking, and gathering possible.',
        unresolved: 'Every tool can protect or destroy depending on how it is used.',
        lesson: 'A good tool makes life less fragile.',
        action: 'Ask what would make your day less fragile by one degree.',
        color: '#C88448',
      },
      {
        era: 'Ancient world',
        title: 'Writing',
        tool: 'memory',
        scene: 'The figure carries a tablet while lines of memory become a shared map.',
        improved: 'Writing let knowledge survive beyond one mind and one lifetime.',
        unresolved: 'Power also learned to write laws, debts, and exclusions.',
        lesson: 'Shared memory changes what a civilisation can coordinate.',
        action: 'Write one clear sentence you do not want to lose.',
        color: '#B89868',
      },
      {
        era: 'Public health',
        title: 'Sanitation',
        tool: 'clean systems',
        scene: 'The figure walks beside water channels drawn as clean blueprint lines.',
        improved: 'Clean water and sanitation saved lives at enormous scale.',
        unresolved: 'Many people still lack the basics that others treat as invisible.',
        lesson: 'Human dignity often begins with infrastructure.',
        action: 'Notice one invisible support that makes your life safer.',
        color: '#78A8A0',
      },
      {
        era: 'Modern medicine',
        title: 'Vaccines And Care',
        tool: 'prevention',
        scene: 'The figure passes a care room, plants, and a small protective halo.',
        improved: 'Medicine turned many fatal threats into preventable or treatable problems.',
        unresolved: 'Care is still unequal, expensive, and emotionally cold in many places.',
        lesson: 'Prevention is one of humanity’s highest forms of kindness.',
        action: 'Choose one small preventive act for your body today.',
        color: '#94B878',
      },
      {
        era: 'Knowledge age',
        title: 'Internet',
        tool: 'connection',
        scene: 'The figure walks through warm network nodes connecting homes and minds.',
        improved: 'The internet gave billions access to knowledge and creative tools.',
        unresolved: 'Connection also became distraction, comparison, and manipulation.',
        lesson: 'Access needs wisdom or it becomes noise.',
        action: 'Use one search today to clarify, not to escape.',
        color: '#78A0B0',
      },
      {
        era: 'Now',
        title: 'AI',
        tool: 'amplified intelligence',
        scene: 'The figure walks beside a soft blueprint constellation that responds to questions.',
        improved: 'AI can help people learn, create, translate, see patterns, and build faster.',
        unresolved: 'Amplification without values can scale confusion and power imbalance.',
        lesson: 'The next tool needs emotional and ethical maturity around it.',
        action: 'Ask AI one question that helps you become clearer or kinder.',
        color: '#70A8A8',
      },
      {
        era: 'Next',
        title: 'Emotional Intelligence',
        tool: 'inner technology',
        scene:
          'The figure walks with open posture while warm lines connect body, people, and world.',
        improved:
          'Learning to regulate, repair, listen, and belong could change the human baseline.',
        unresolved:
          'We still treat inner life as private weakness instead of public infrastructure.',
        lesson: 'The future is not only smarter machines. It is wiser humans.',
        action: 'Make one small repair: a breath, a message, a pause, or an honest sentence.',
        color: '#D0A068',
      },
    ],
  },
  {
    key: 'democracy',
    title: 'History Of Democracy',
    subtitle: 'How humans learned to share power.',
    question: 'Is representative democracy the final form, or one step in a longer evolution?',
    steps: [
      {
        era: 'Early groups',
        title: 'Councils',
        tool: 'shared voice',
        scene: 'The walking figure passes a circle of people around a warm center.',
        improved: 'Groups survived by listening, negotiating, and remembering each other.',
        unresolved: 'Power often stayed with the strongest, oldest, richest, or loudest.',
        lesson: 'Democracy begins when more voices matter.',
        action: 'Ask whose voice is missing from a decision you care about.',
        color: '#C69A62',
      },
      {
        era: 'Athens',
        title: 'Citizen Assembly',
        tool: 'public decision',
        scene: 'The figure passes an open civic square drawn like a blueprint amphitheater.',
        improved: 'Citizens could deliberate and decide together.',
        unresolved: 'Many people were excluded: women, enslaved people, foreigners.',
        lesson: 'A breakthrough can still be incomplete.',
        action: 'Hold both truths: progress happened, and exclusion remained.',
        color: '#B8A06A',
      },
      {
        era: 'Rights era',
        title: 'Expanding The Vote',
        tool: 'inclusion',
        scene: 'The figure’s path widens as more silhouettes join from the margins.',
        improved: 'Voting rights expanded across class, race, and gender through long struggle.',
        unresolved: 'Access, representation, money, and manipulation still shape outcomes.',
        lesson: 'Democracy is not a finished object. It is a maintenance practice.',
        action: 'Learn one local decision pathway where your voice can matter.',
        color: '#A8B878',
      },
      {
        era: 'Digital age',
        title: 'Networked Publics',
        tool: 'instant participation',
        scene: 'The figure walks through a public square made of glowing nodes.',
        improved: 'People can organise, learn, publish, and mobilise faster than before.',
        unresolved: 'Speed also spreads outrage, misinformation, and tribal fear.',
        lesson: 'Participation needs attention, trust, and good information design.',
        action: 'Before sharing, pause and ask what this information makes possible.',
        color: '#78A0B0',
      },
      {
        era: 'Future',
        title: 'AI-Assisted Governance',
        tool: 'collective intelligence',
        scene: 'The figure approaches a transparent assembly table with human and machine signals.',
        improved:
          'Machines could help summarise, simulate, translate, and reveal policy tradeoffs.',
        unresolved: 'Machines could also centralise power and hide bias behind complexity.',
        lesson: 'Better governance needs better humans and transparent tools.',
        action: 'Imagine one decision where clarity would reduce conflict.',
        color: '#70A8A8',
      },
    ],
  },
  {
    key: 'world-peace',
    title: 'History Of World Peace',
    subtitle: 'How cooperation slowly became a civilisational technology.',
    question: 'Is world peace naive, or a system humanity has not fully built yet?',
    steps: [
      {
        era: 'Early law',
        title: 'Rules Against Chaos',
        tool: 'law',
        scene: 'The figure walks from scattered conflict marks toward a simple shared boundary.',
        improved: 'Laws began to limit revenge and make behaviour more predictable.',
        unresolved: 'Law often protected insiders more than outsiders.',
        lesson: 'Peace begins when force is no longer the only language.',
        action: 'Choose one boundary that creates safety rather than punishment.',
        color: '#B89068',
      },
      {
        era: 'Diplomacy',
        title: 'Treaties',
        tool: 'agreement',
        scene: 'The figure crosses a bridge between two warm city silhouettes.',
        improved: 'Treaties made it possible for enemies to create rules after conflict.',
        unresolved: 'Agreements fail when fear, humiliation, or incentives remain unchanged.',
        lesson: 'Peace needs structure and emotional repair.',
        action: 'In one conflict, ask what agreement would make both sides safer.',
        color: '#C0A060',
      },
      {
        era: 'Humanitarian era',
        title: 'Protecting Civilians',
        tool: 'human dignity',
        scene: 'The figure passes care tents, helpers, and protected paths through danger.',
        improved: 'Humanitarian movements insisted that even war needs limits.',
        unresolved: 'The world still fails many civilians when power ignores dignity.',
        lesson: 'Universal care is one of the roots of peace.',
        action: 'Practice seeing the human being before the side they belong to.',
        color: '#A8B078',
      },
      {
        era: 'Global institutions',
        title: 'United Nations',
        tool: 'world forum',
        scene: 'The figure enters a circular world room with many paths converging.',
        improved: 'Humanity built institutions to talk before, during, and after crises.',
        unresolved: 'Institutions remain limited by power, vetoes, interests, and distrust.',
        lesson: 'A world forum is imperfect, but silence is worse.',
        action: 'Ask what level of conversation is missing before a problem becomes a crisis.',
        color: '#78A0B0',
      },
      {
        era: 'Future',
        title: 'Peace Systems',
        tool: 'early repair',
        scene:
          'The figure walks through a living map that detects pressure and opens repair paths.',
        improved:
          'AI, education, diplomacy, and emotional intelligence could help prevent conflict earlier.',
        unresolved: 'Prevention requires trust before emergency, not only response after damage.',
        lesson: 'World peace may be a design problem as much as a dream.',
        action: 'Create peace at the smallest scale: one calmer reply, one repair, one bridge.',
        color: '#70A8A8',
      },
    ],
  },
  {
    key: 'kindness',
    title: 'History Of Kindness',
    subtitle: 'How care expanded from the tribe toward wider circles.',
    question: 'What made humans widen the circle of who deserves care?',
    steps: [
      {
        era: 'Kinship',
        title: 'Care For Our Own',
        tool: 'belonging',
        scene: 'The figure walks beside a small shelter and shared food.',
        improved: 'Care inside close groups helped humans survive.',
        unresolved: 'Care often stopped at the border of the group.',
        lesson: 'Kindness begins near, but it can grow outward.',
        action: 'Offer one small care act to someone close today.',
        color: '#C88E68',
      },
      {
        era: 'Hospitals and charity',
        title: 'Organised Care',
        tool: 'institutions',
        scene: 'The figure passes a warm care house with helpers and plants.',
        improved: 'Humans built places where strangers could be helped.',
        unresolved: 'Care could still be paternalistic, unequal, or conditional.',
        lesson: 'Kindness becomes powerful when it becomes organised.',
        action: 'Make one useful support easier for someone to receive.',
        color: '#B8A060',
      },
      {
        era: 'Human rights',
        title: 'Dignity For All',
        tool: 'universal worth',
        scene: 'The figure walks as many different silhouettes join the road.',
        improved: 'The idea of universal dignity expanded who counts.',
        unresolved: 'Declaring rights is easier than protecting them everywhere.',
        lesson: 'The circle of care must be defended in practice.',
        action: 'Speak or act once for someone’s dignity when it is easy to ignore.',
        color: '#A8B878',
      },
      {
        era: 'Future',
        title: 'Kind Systems',
        tool: 'designed care',
        scene: 'The figure walks through a city where systems guide people toward help early.',
        improved:
          'Future kindness could be built into schools, cities, healthcare, and technology.',
        unresolved: 'Efficiency without tenderness can still feel inhuman.',
        lesson: 'The best systems make care easier to give and receive.',
        action: 'Simplify one small process so care can flow with less friction.',
        color: '#D0A068',
      },
    ],
  },
  {
    key: 'womens-freedom',
    title: 'History Of Women’s Freedom',
    subtitle: 'How humanity grows when women’s lives open.',
    question: 'What becomes possible when half of humanity is freer, safer, educated, and heard?',
    steps: [
      {
        era: 'Restricted worlds',
        title: 'The Margin',
        tool: 'recognition',
        scene:
          'The walking figure passes a doorway where another figure stands at the edge of the map.',
        improved:
          'Across cultures, women still created knowledge, care, art, and survival under constraint.',
        unresolved: 'Law, violence, custom, and economics often limited women’s agency.',
        lesson: 'A society loses intelligence when it silences women.',
        action: 'Notice one place where a woman’s voice changed what was possible.',
        color: '#B88A78',
      },
      {
        era: 'Education',
        title: 'Learning Opens',
        tool: 'knowledge',
        scene: 'The figure walks beside open books, tools, and a brighter path.',
        improved: 'Education expanded women’s agency, health, income, and public voice.',
        unresolved: 'Access and safety remain unequal across the world.',
        lesson: 'Educating girls is one of the highest-leverage forms of progress.',
        action: 'Support one learning path, your own or someone else’s.',
        color: '#B8A060',
      },
      {
        era: 'Voting rights',
        title: 'Political Voice',
        tool: 'representation',
        scene: 'The figure walks into a public square with women at the center, not the edge.',
        improved: 'Suffrage changed who could shape laws and institutions.',
        unresolved: 'Representation still does not guarantee safety, equity, or respect.',
        lesson: 'A voice in the system changes the system’s imagination.',
        action: 'Ask who is affected by a decision and whether they are present.',
        color: '#A8B878',
      },
      {
        era: 'Future',
        title: 'Shared Flourishing',
        tool: 'partnership',
        scene: 'Two figures walk forward with equal scale, shared tools, and open horizon.',
        improved:
          'A freer future is not women against men, but humanity with more of its intelligence available.',
        unresolved: 'Freedom must include safety, care, economics, body, time, and voice.',
        lesson: 'Equality is not a side issue. It is civilisational intelligence.',
        action: 'Practice respect as design: who has time, safety, voice, and choice?',
        color: '#D0A068',
      },
    ],
  },
  {
    key: 'animals',
    title: 'History Of Animals In Human Consciousness',
    subtitle: 'How the circle of care can expand beyond humans.',
    question: 'What does our treatment of animals reveal about our emotional evolution?',
    steps: [
      {
        era: 'Survival',
        title: 'Use And Dependence',
        tool: 'relationship',
        scene: 'The figure walks beside animal silhouettes used for food, movement, and work.',
        improved: 'Humans survived through deep dependence on animals.',
        unresolved: 'Dependence often became domination without attention to suffering.',
        lesson: 'Power creates responsibility.',
        action: 'Notice one living being your comfort depends on.',
        color: '#B89068',
      },
      {
        era: 'Companionship',
        title: 'Animals Near The Fire',
        tool: 'bond',
        scene: 'The figure walks with a dog-like companion near warm homes.',
        improved: 'Companion animals revealed affection across species.',
        unresolved: 'Love for some animals coexisted with indifference to others.',
        lesson: 'Closeness teaches empathy first, then ethics must widen it.',
        action: 'Give one moment of attention to a non-human life today.',
        color: '#C0A060',
      },
      {
        era: 'Welfare',
        title: 'Reducing Suffering',
        tool: 'care standards',
        scene: 'The figure passes shelters, open fields, and gentler handling systems.',
        improved: 'Animal welfare movements made suffering visible and politically discussable.',
        unresolved: 'Industrial systems still hide enormous amounts of pain.',
        lesson: 'What is hidden from view still matters morally.',
        action: 'Make one consumption choice with more awareness.',
        color: '#A8B878',
      },
      {
        era: 'Future',
        title: 'Kinship With Life',
        tool: 'ecological empathy',
        scene:
          'The figure walks through a living field where humans, animals, plants, and systems connect.',
        improved: 'A wiser civilisation may treat life as relationship, not only resource.',
        unresolved: 'Care has to become practical at scale, not only sentimental.',
        lesson: 'A beautiful future includes how gently we hold other life.',
        action: 'Choose one small act that makes your relationship to life less extractive.',
        color: '#7FA878',
      },
    ],
  },
  {
    key: 'happiness',
    title: 'History Of Happiness',
    subtitle: 'What humans have believed makes life good.',
    question:
      'What should we keep from the past, and what is happiness asking us to understand now?',
    steps: [
      {
        era: 'Ancient virtue',
        title: 'A Good Life',
        tool: 'character',
        scene: 'The figure walks beside a simple temple, garden, and balanced path.',
        improved:
          'Many traditions understood happiness as a trained way of living, not just pleasure.',
        unresolved: 'Virtue can become rigid when it forgets tenderness.',
        lesson: 'Happiness grows when action and values align.',
        action: 'Choose one small act that matches the person you want to become.',
        color: '#C0A060',
      },
      {
        era: 'Harmony traditions',
        title: 'Belonging To The Whole',
        tool: 'harmony',
        scene: 'The figure walks through a garden where paths, people, and nature balance.',
        improved: 'Many cultures taught that wellbeing depends on relationship, rhythm, and place.',
        unresolved: 'Harmony can suppress truth if conflict is never allowed.',
        lesson: 'Peace is not silence. It is relationship that can hold truth.',
        action: 'Restore one small harmony: space, body, room, or relationship.',
        color: '#A8B878',
      },
      {
        era: 'Modern freedom',
        title: 'Choice And Selfhood',
        tool: 'agency',
        scene: 'The figure walks past many open doors and possible lives.',
        improved: 'Modernity expanded choice, self-expression, and personal freedom.',
        unresolved: 'Too much choice without meaning can become anxiety.',
        lesson: 'Freedom needs direction.',
        action: 'Name one thing you choose because it truly matters to you.',
        color: '#D0A068',
      },
      {
        era: 'Science of wellbeing',
        title: 'What Helps',
        tool: 'evidence',
        scene:
          'The figure walks through a warm blueprint of sleep, movement, connection, meaning, and care.',
        improved: 'Research increasingly shows the practical foundations of wellbeing.',
        unresolved:
          'Knowing what helps is not the same as building a life or society that supports it.',
        lesson: 'Happiness is personal and structural.',
        action: 'Improve one foundation today: sleep, movement, connection, meaning, or kindness.',
        color: '#78A8A0',
      },
      {
        era: 'Future',
        title: 'Collective Happiness',
        tool: 'shared flourishing',
        scene:
          'The figure joins others on a warm map where lights spread across homes, gardens, schools, and tools.',
        improved: 'A more emotionally intelligent world could make happiness less accidental.',
        unresolved: 'We still confuse growth, status, and attention with a good life.',
        lesson: 'Human potential for happiness is enormous when systems support what souls need.',
        action: 'Build one small condition for happiness, not only one moment of pleasure.',
        color: '#D8C878',
      },
    ],
  },
];
