/**
 * Runs at prebuild / predev.
 * Reads the last 30 git commits and writes lib/generated/changelog.ts
 * so ColourmapBrandButton always shows real history without manual updates.
 */
import { execSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';

function run(cmd: string): string {
  try {
    return execSync(cmd, { encoding: 'utf-8' }).trim();
  } catch {
    return '';
  }
}

// Read each field separately to avoid shell pipe/separator conflicts on Windows.
const hashes = run('git log --format=%H --date=short -30').split('\n').filter(Boolean);
const subjects = run('git log --format=%s --date=short -30').split('\n').filter(Boolean);
const dates = run('git log --format=%ad --date=short -30').split('\n').filter(Boolean);
const branch = run('git branch --show-current') || 'main';
const latestHash = run('git rev-parse --short HEAD') || '';

interface Entry {
  hash: string;
  subject: string;
  date: string;
  prNum: number | null;
}

const entries: Entry[] = hashes
  .map((hash, i) => {
    const subject = subjects[i] ?? '';
    const date = dates[i] ?? '';
    const prMatch = subject.match(/#(\d+)/);
    const prNum = prMatch ? Number.parseInt(prMatch[1], 10) : null;
    const clean =
      subject
        .replace(/^Merge pull request #\d+ from \S+\/?/, '')
        .replace(/^Merge remote-tracking branch '.+' into .+/, 'sync with main')
        .replace(/\(#\d+\)$/, '')
        .trim() || subject;
    return { hash: hash.slice(0, 7), subject: clean, date, prNum };
  })
  .filter((e) => e.subject && !e.subject.startsWith("Merge branch 'main'"));

mkdirSync('lib/generated', { recursive: true });

const content = `// AUTO-GENERATED by scripts/gen-changelog.ts — do not edit by hand.
// Re-runs on every \`bun run dev\` and \`bun run build\`.

export interface ChangelogEntry {
  hash: string;
  subject: string;
  date: string;
  prNum: number | null;
}

export const CURRENT_BRANCH = ${JSON.stringify(branch)};
export const LATEST_HASH = ${JSON.stringify(latestHash)};
export const BUILD_DATE = ${JSON.stringify(new Date().toISOString().slice(0, 10))};

export const CHANGELOG: ChangelogEntry[] = ${JSON.stringify(entries, null, 2)};
`;

writeFileSync('lib/generated/changelog.ts', content);
console.log(
  `gen-changelog: wrote ${entries.length} entries (branch: ${branch}, head: ${latestHash})`,
);
